name: Build & Cache flake outputs

on: push

jobs:
  build-and-cache:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ secrets.ATTIC_SERVER }}
          token: ${{ secrets.ATTIC_TOKEN }}
          cache: nixos

      - name: Install omnix
        run: nix profile install "github:juspay/omnix"

      - name: Build all flake outputs
        run: om ci run --extra-access-tokens ${{ secrets.GITHUB_TOKEN }}
